import React, { useEffect, useMemo, useState } from 'react';
import './Dashboard.css';

const roles = ['University Management', 'Registry / Admin', 'Lecturer', 'Academic Adviser', 'Finance', 'Student'];
const coreNav = ['Overview', 'Students', 'Academics', 'Timetable', 'Registration', 'Results', 'Finance', 'Registry', 'Advising', 'Resources', 'Attendance', 'Assignments', 'Analytics'];

const studentsSeed = [
  { id:'MST/23/0412', name:'Amina Bello', program:'B.Sc. Computer Science', faculty:'Computing & Digital Sciences', level:'300', cgpa:4.21, status:'Good standing', email:'amina.bello@masta.edu', phone:'+234 803 555 0192', adviser:'Dr. Halima Yusuf' },
  { id:'MST/22/0198', name:'Mohammed Umar', program:'B.Sc. Economics', faculty:'Management & Social Sciences', level:'400', cgpa:1.72, status:'Academic warning', email:'mohammed.umar@masta.edu', phone:'+234 806 112 0455', adviser:'Dr. Kunle Adebayo' },
  { id:'MST/24/0881', name:'Tomi Adeyemi', program:'B.Eng. Civil Engineering', faculty:'Engineering', level:'200', cgpa:3.68, status:'Good standing', email:'tomi.adeyemi@masta.edu', phone:'+234 809 611 2210', adviser:'Engr. Efe Okoro' },
  { id:'MST/23/0517', name:'David James', program:'B.Sc. Accounting', faculty:'Management & Social Sciences', level:'300', cgpa:3.12, status:'Registration pending', email:'david.james@masta.edu', phone:'+234 703 446 6119', adviser:'Mrs. Nneka Obi' },
  { id:'MST/21/0034', name:'Zainab Ibrahim', program:'LL.B. Law', faculty:'Law', level:'500', cgpa:4.57, status:'Graduation review', email:'zainab.ibrahim@masta.edu', phone:'+234 802 908 3177', adviser:'Dr. Nura Bello' },
];

const courses = [
  { code:'CSC301', title:'Algorithms & Complexity', credit:3, lecturer:'Dr. Musa Ibrahim', room:'ICT 204', students:86 },
  { code:'CSC303', title:'Database Systems', credit:3, lecturer:'Dr. Sarah Okafor', room:'ICT 102', students:84 },
  { code:'CSC305', title:'Operating Systems', credit:3, lecturer:'Dr. Kabiru Abdullahi', room:'ICT 301', students:81 },
  { code:'CSC307', title:'Software Engineering', credit:3, lecturer:'Engr. Tola Martins', room:'LT B', students:88 },
  { code:'MTH311', title:'Numerical Methods', credit:3, lecturer:'Dr. Joy Eze', room:'SCI 105', students:72 },
  { code:'GST301', title:'Entrepreneurship & Innovation', credit:2, lecturer:'Mrs. Dami Adewale', room:'LT A', students:210 },
];

const currentStudent = {
  id:'MST/23/0412', name:'Amina Bello', programme:'B.Sc. Computer Science', department:'Computer Science',
  level:'300', session:'2026/2027', semester:'First Semester', registeredCourses:['CSC301','CSC303','CSC305','CSC307','MTH311','GST301']
};

const timetableSeed = [
  // Computer Science — 100 Level
  { id:101, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'100', code:'CSC101', title:'Introduction to Computer Science', day:'Monday', start:'08:00', end:'10:00', room:'ICT 101', lecturer:'Dr. Sarah Okafor', type:'Lecture' },
  { id:102, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'100', code:'MTH101', title:'Elementary Mathematics I', day:'Tuesday', start:'10:00', end:'12:00', room:'SCI 201', lecturer:'Dr. Joy Eze', type:'Lecture' },
  { id:103, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'100', code:'GST101', title:'Communication in English', day:'Thursday', start:'12:00', end:'14:00', room:'LT A', lecturer:'Mrs. Dami Adewale', type:'Lecture' },

  // Computer Science — 200 Level
  { id:201, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'200', code:'CSC201', title:'Data Structures', day:'Monday', start:'11:00', end:'13:00', room:'ICT 201', lecturer:'Dr. Kabiru Abdullahi', type:'Lecture' },
  { id:202, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'200', code:'CSC203', title:'Computer Architecture', day:'Wednesday', start:'09:00', end:'11:00', room:'ICT 202', lecturer:'Engr. Tola Martins', type:'Lecture' },
  { id:203, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'200', code:'CSC205', title:'Object-Oriented Programming', day:'Friday', start:'10:00', end:'12:00', room:'ICT Lab 1', lecturer:'Dr. Sarah Okafor', type:'Lab' },

  // Computer Science — 300 Level / Amina Bello's current academic context
  { id:301, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'CSC301', title:'Algorithms & Complexity', day:'Monday', start:'10:00', end:'12:00', room:'ICT 204', lecturer:'Dr. Ibrahim', type:'Lecture' },
  { id:302, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'CSC303', title:'Database Systems', day:'Monday', start:'13:00', end:'15:00', room:'ICT 102', lecturer:'Dr. Sarah Okafor', type:'Lecture' },
  { id:303, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'CSC305', title:'Operating Systems', day:'Tuesday', start:'10:00', end:'12:00', room:'ICT 301', lecturer:'Dr. Kabiru Abdullahi', type:'Lecture' },
  { id:304, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'MTH311', title:'Numerical Methods', day:'Wednesday', start:'08:00', end:'10:00', room:'SCI 105', lecturer:'Dr. Joy Eze', type:'Lecture' },
  { id:305, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'CSC307', title:'Software Engineering', day:'Thursday', start:'11:00', end:'13:00', room:'LT B', lecturer:'Engr. Tola Martins', type:'Lecture' },
  { id:306, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'300', code:'GST301', title:'Entrepreneurship & Innovation', day:'Friday', start:'10:00', end:'12:00', room:'LT A', lecturer:'Mrs. Dami Adewale', type:'Lecture' },

  // Computer Science — 400 Level
  { id:401, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'400', code:'CSC401', title:'Advanced Algorithms', day:'Thursday', start:'09:00', end:'11:00', room:'ICT 401', lecturer:'Dr. Ibrahim', type:'Lecture' },
  { id:402, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'400', code:'CSC403', title:'Artificial Intelligence', day:'Tuesday', start:'09:00', end:'11:00', room:'ICT Lab 3', lecturer:'Dr. Sarah Okafor', type:'Lecture' },
  { id:403, session:'2026/2027', semester:'First Semester', department:'Computer Science', programme:'B.Sc. Computer Science', level:'400', code:'CSC405', title:'Computer Security', day:'Friday', start:'13:00', end:'15:00', room:'ICT 405', lecturer:'Dr. Kabiru Abdullahi', type:'Lecture' },

  // Cross-department lecturer allocation — Dr. Ibrahim
  { id:501, session:'2026/2027', semester:'First Semester', department:'Software Engineering', programme:'B.Sc. Software Engineering', level:'200', code:'SEN205', title:'Software Design Fundamentals', day:'Tuesday', start:'14:00', end:'16:00', room:'SEN 205', lecturer:'Dr. Ibrahim', type:'Lecture' },
];

const materialsSeed = [
  { id:1, code:'CSC301', title:'Week 1 — Algorithm Analysis', kind:'Lecture slides', size:'2.4 MB', date:'01 Sep 2026', lecturer:'Dr. Musa Ibrahim' },
  { id:2, code:'CSC301', title:'Complexity Practice Problems', kind:'Worksheet', size:'780 KB', date:'02 Sep 2026', lecturer:'Dr. Musa Ibrahim' },
  { id:3, code:'CSC303', title:'Relational Database Design', kind:'Lecture notes', size:'1.8 MB', date:'31 Aug 2026', lecturer:'Dr. Sarah Okafor' },
  { id:4, code:'CSC305', title:'Processes & Threads', kind:'Reading', size:'1.1 MB', date:'03 Sep 2026', lecturer:'Dr. Kabiru Abdullahi' },
  { id:5, code:'CSC307', title:'Software Development Lifecycle', kind:'Lecture slides', size:'3.0 MB', date:'03 Sep 2026', lecturer:'Engr. Tola Martins' },
];

const documentsSeed = [
  { id:1, title:'Admission Letter', category:'Official', date:'18 Aug 2023', type:'PDF' },
  { id:2, title:'2026/27 Registration Slip', category:'Academic', date:'29 Aug 2026', type:'PDF' },
  { id:3, title:'First Semester Fee Receipt', category:'Finance', date:'25 Aug 2026', type:'PDF' },
  { id:4, title:'Student ID Verification', category:'Identity', date:'01 Sep 2026', type:'PDF' },
];

const assignmentsSeed = [
  { id:1, code:'CSC301', title:'Asymptotic Complexity Problem Set', due:'2026-09-08', points:20, status:'Open', instructions:'Solve all six questions and show your working. Submit one PDF.', submissions:57 },
  { id:2, code:'CSC303', title:'ERD Design Exercise', due:'2026-09-10', points:15, status:'Open', instructions:'Model the supplied university library scenario using an ER diagram.', submissions:44 },
  { id:3, code:'CSC307', title:'Requirements Specification', due:'2026-09-14', points:25, status:'Open', instructions:'Submit a concise SRS for your semester group project.', submissions:18 },
];

const gradeRows = [
  ['CSC201','Data Structures',3,'A',5,15],['CSC203','Computer Architecture',3,'B',4,12],['CSC205','Object-Oriented Programming',3,'A',5,15],['MTH201','Discrete Mathematics',3,'B',4,12],['GST201','Communication Skills',2,'A',5,10],
  ['CSC211','Web Technologies',3,'A',5,15],['CSC213','Computer Networks',3,'A',5,15],['CSC215','Systems Analysis',3,'B',4,12],['MTH211','Linear Algebra',3,'C',3,9],['GST211','Leadership Studies',2,'A',5,10],
];

const attendanceStudentsSeed = [
  { id:'MST/23/0412', name:'Amina Bello', present:true },
  { id:'MST/23/0428', name:'Chinedu Okafor', present:true },
  { id:'MST/23/0431', name:'Fatima Garba', present:true },
  { id:'MST/23/0440', name:'Joshua Mensah', present:false },
  { id:'MST/23/0443', name:'Maryam Sule', present:true },
  { id:'MST/23/0451', name:'Samuel Eze', present:false },
  { id:'MST/23/0467', name:'Hauwa Aliyu', present:true },
  { id:'MST/23/0472', name:'Tunde Balogun', present:true },
];

function useStoredState(key, initialValue) {
  const [value, setValue] = useState(() => {
    try { const saved = localStorage.getItem(key); return saved ? JSON.parse(saved) : initialValue; } catch { return initialValue; }
  });
  useEffect(() => { localStorage.setItem(key, JSON.stringify(value)); }, [key, value]);
  return [value, setValue];
}

const initials = (name) => name.split(' ').map(x => x[0]).join('').slice(0,2);
const fmtDate = (d) => new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});

function Icon({ name }) {
  const glyphs = { Overview:'⌂', Students:'◎', Academics:'◇', Timetable:'▦', Registration:'✓', Results:'▥', Finance:'₦', Registry:'▤', Advising:'◉', Resources:'▱', Attendance:'☑', Assignments:'✎', Analytics:'⌁' };
  return <span className="nav-glyph">{glyphs[name] || '•'}</span>;
}

const Kpi = ({label,value,meta,tone}) => <div className="kpi-card"><div className="kpi-label"><span>{label}</span><i className={tone||''}></i></div><strong>{value}</strong><small>{meta}</small></div>;

function Empty({ title, text }) { return <div className="empty"><div>◇</div><b>{title}</b><span>{text}</span></div>; }

function Modal({ title, subtitle, children, onClose, wide=false }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><div className={`modal ${wide?'wide':''}`} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h3>{title}</h3><p>{subtitle}</p></div><button onClick={onClose}>×</button></div>{children}</div></div>;
}

function Overview({ setActive }) {
  return <>
    <div className="page-heading"><div><span className="section-kicker">INSTITUTIONAL OVERVIEW</span><h1>Good afternoon, Prof. Adeyemi.</h1><p>Here is what is happening across Masta Demo University today.</p></div><button className="soft-btn">2026/27 · First Semester⌄</button></div>
    <div className="kpi-grid"><Kpi label="Active students" value="14,821" meta="+4.8% from last session" tone="green"/><Kpi label="Registration completion" value="91.4%" meta="1,274 students outstanding"/><Kpi label="Fees collected" value="₦7.2bn" meta="82.8% of ₦8.7bn expected"/><Kpi label="Students at risk" value="421" meta="38 require urgent review" tone="amber"/></div>
    <div className="dashboard-grid two-one">
      <section className="panel"><div className="panel-head"><div><h3>Student lifecycle</h3><p>Current movement through the academic session.</p></div><button>View report</button></div><div className="funnel-list">{[['Applications','23,415','100%'],['Offers issued','6,820','29%'],['Accepted','5,914','25%'],['Registered','5,312','23%']].map(([a,b,c])=><div key={a}><span>{a}</span><b>{b}</b><div className="bar"><i style={{width:c}}></i></div><em>{c}</em></div>)}</div></section>
      <section className="panel attention"><div className="panel-head"><div><h3>Needs attention</h3><p>Items requiring institutional action.</p></div></div>{[['1,274','Incomplete registration','Deadline in 6 days','Registration'],['18','Grade batches awaiting approval','Across 7 departments','Results'],['421','Students academically at risk','38 high priority cases','Advising']].map(x=><button key={x[1]} onClick={()=>setActive(x[3])}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><strong>→</strong></button>)}</section>
    </div>
    <div className="dashboard-grid two-one bottom-grid">
      <section className="panel"><div className="panel-head"><div><h3>Academic performance</h3><p>CGPA distribution across active students.</p></div><span className="metric-chip">Institution avg. 3.16</span></div><div className="chart-bars">{[['4.50–5.00',23],['3.50–4.49',68],['2.40–3.49',82],['1.50–2.39',37],['Below 1.50',14]].map(([x,y])=><div key={x}><div><i style={{height:`${y}%`}}></i></div><span>{x}</span></div>)}</div></section>
      <section className="panel"><div className="panel-head"><div><h3>Collection progress</h3><p>Student finance this session.</p></div></div><div className="donut-wrap"><div className="donut"><div><b>82.8%</b><span>collected</span></div></div><div className="finance-mini"><span><i></i>Collected <b>₦7.2bn</b></span><span><i></i>Outstanding <b>₦1.5bn</b></span></div></div></section>
    </div>
  </>;
}

function StudentHome({ setActive, timetable, assignments }) {
  const next = timetable[0];
  return <>
    <div className="student-hero"><div><span className="section-kicker light">STUDENT HOME</span><h1>Welcome back, Amina.</h1><p>B.Sc. Computer Science · 300 Level · 2026/27 First Semester</p></div><div className="student-id-card"><span>STUDENT ID</span><b>MST/23/0412</b><small>Good standing</small></div></div>
    <div className="kpi-grid"><Kpi label="Current CGPA" value="4.21" meta="Second Class Upper · +0.12" tone="green"/><Kpi label="Registered credits" value="17" meta="6 courses this semester"/><Kpi label="Attendance" value="92%" meta="Above 75% requirement"/><Kpi label="Outstanding balance" value="₦75,000" meta="Next payment due 30 Sep" tone="amber"/></div>
    <div className="dashboard-grid two-one">
      <section className="panel"><div className="panel-head"><div><h3>Today</h3><p>Your academic schedule and deadlines.</p></div><button onClick={()=>setActive('Timetable')}>Full timetable</button></div>
        <div className="today-class"><div className="time-block"><b>{next?.start}</b><small>{next?.end}</small></div><div><span className="course-chip">{next?.code}</span><h3>{next?.title}</h3><p>{next?.room} · {next?.lecturer}</p></div><strong>→</strong></div>
        <div className="student-actions"><button onClick={()=>setActive('Resources')}><span>▱</span><b>Learning resources</b><small>5 new materials</small></button><button onClick={()=>setActive('Results')}><span>▥</span><b>Results & transcript</b><small>View academic record</small></button><button onClick={()=>setActive('Assignments')}><span>✎</span><b>Assignments</b><small>{assignments.filter(a=>a.status==='Open').length} active</small></button></div>
      </section>
      <section className="panel"><div className="panel-head"><div><h3>Degree progress</h3><p>Progress towards graduation.</p></div><span className="metric-chip">78%</span></div><div className="degree-ring"><div><b>94</b><span>of 120 credits</span></div></div><div className="check-list"><p>✓ Core courses <b>32 / 36</b></p><p>✓ Electives <b>18 / 24</b></p><p>! Final year project <b>Pending</b></p></div></section>
    </div>
  </>;
}

function Students() {
  const [q,setQ]=useState(''); const [selected,setSelected]=useState(null); const data=useMemo(()=>studentsSeed.filter(s=>(s.name+s.id+s.program).toLowerCase().includes(q.toLowerCase())),[q]);
  return <><div className="page-heading"><div><span className="section-kicker">STUDENT RECORDS</span><h1>Students</h1><p>One authoritative record across the entire student lifecycle.</p></div><button className="primary-btn">+ Add student</button></div><div className="toolbar"><div className="search">⌕ <input placeholder="Search name, matric no. or programme" value={q} onChange={e=>setQ(e.target.value)}/></div><button>All faculties⌄</button><button>All statuses⌄</button><button>Export</button></div><section className="panel table-panel"><table><thead><tr><th>Student</th><th>Programme</th><th>Level</th><th>CGPA</th><th>Status</th><th></th></tr></thead><tbody>{data.map(s=><tr key={s.id} onClick={()=>setSelected(s)} className="click-row"><td><div className="student-cell"><span>{initials(s.name)}</span><div><b>{s.name}</b><small>{s.id}</small></div></div></td><td>{s.program}</td><td>{s.level} Level</td><td><b>{s.cgpa}</b></td><td><span className={`status ${s.status.includes('warning')?'warn':s.status.includes('pending')?'pending':''}`}>{s.status}</span></td><td>•••</td></tr>)}</tbody></table></section>{selected&&<Modal title={selected.name} subtitle={`${selected.id} · ${selected.program}`} onClose={()=>setSelected(null)}><div className="profile-grid"><div><span>Email</span><b>{selected.email}</b></div><div><span>Phone</span><b>{selected.phone}</b></div><div><span>Faculty</span><b>{selected.faculty}</b></div><div><span>Academic adviser</span><b>{selected.adviser}</b></div><div><span>CGPA</span><b>{selected.cgpa}</b></div><div><span>Status</span><b>{selected.status}</b></div></div></Modal>}</>;
}

function Academics() { return <><div className="page-heading"><div><span className="section-kicker">ACADEMIC STRUCTURE</span><h1>Academics</h1><p>Programmes, curricula, courses and teaching activity in one place.</p></div><button className="primary-btn">+ New course</button></div><div className="kpi-grid"><Kpi label="Faculties" value="8" meta="31 departments"/><Kpi label="Programmes" value="54" meta="44 undergraduate · 10 postgraduate"/><Kpi label="Active courses" value="612" meta="First semester offerings"/><Kpi label="Teaching staff" value="487" meta="92% course allocation complete"/></div><div className="dashboard-grid two-one"><section className="panel"><div className="panel-head"><div><h3>Programme catalogue</h3><p>Current academic programmes by faculty.</p></div><button>Manage curriculum</button></div>{['Computing & Digital Sciences','Engineering','Management & Social Sciences','Law','Health Sciences'].map((f,i)=><div className="programme-row" key={f}><span>{String(i+1).padStart(2,'0')}</span><div><b>{f}</b><small>{[8,9,12,4,7][i]} programmes · {[74,103,128,42,91][i]} courses</small></div><strong>→</strong></div>)}</section><section className="panel"><div className="panel-head"><div><h3>Curriculum health</h3><p>Automated configuration checks.</p></div></div><div className="health-score"><b>94%</b><span>Curricula fully configured</span></div><div className="check-list"><p>✓ 48 programmes validated</p><p>! 4 programmes missing elective rules</p><p>! 2 prerequisite conflicts detected</p></div></section></div></> }

function Timetable({ role, timetable, setTimetable, pushNotice }) {
  const days=['Monday','Tuesday','Wednesday','Thursday','Friday'];
  const canEdit = role === 'Registry / Admin';
  const [editing,setEditing]=useState(null);
  const [adding,setAdding]=useState(false);
  const [filters,setFilters]=useState({session:'2026/2027',semester:'First Semester',department:'Computer Science',programme:'B.Sc. Computer Science',level:'300'});

  const studentTimetable = timetable.filter(item =>
    item.session===currentStudent.session && item.semester===currentStudent.semester &&
    currentStudent.registeredCourses.includes(item.code)
  );
  const lecturerTimetable = timetable.filter(item => item.lecturer==='Dr. Ibrahim' && item.session==='2026/2027' && item.semester==='First Semester');
  const adminTimetable = timetable.filter(item =>
    item.session===filters.session && item.semester===filters.semester && item.department===filters.department &&
    item.programme===filters.programme && item.level===filters.level
  );
  const visibleTimetable = role==='Student' ? studentTimetable : role==='Lecturer' ? lecturerTimetable : canEdit ? adminTimetable : timetable.filter(x=>x.session==='2026/2027'&&x.semester==='First Semester'&&x.department==='Computer Science'&&x.level==='300');

  const saveEdit=(e)=>{
    e.preventDefault(); const fd=new FormData(e.currentTarget);
    const updated={...editing,session:fd.get('session'),semester:fd.get('semester'),department:fd.get('department'),programme:fd.get('programme'),level:fd.get('level'),code:fd.get('code'),title:fd.get('title'),lecturer:fd.get('lecturer'),type:fd.get('type'),day:fd.get('day'),start:fd.get('start'),end:fd.get('end'),room:fd.get('room')};
    setTimetable(t=>t.map(x=>x.id===updated.id?updated:x));
    pushNotice(`Timetable updated: ${updated.code} · ${updated.programme} ${updated.level} Level · ${updated.day} ${updated.start}–${updated.end}.`);
    setEditing(null);
  };

  const addClass=(e)=>{
    e.preventDefault(); const fd=new FormData(e.currentTarget);
    const item={id:Date.now(),session:fd.get('session'),semester:fd.get('semester'),department:fd.get('department'),programme:fd.get('programme'),level:fd.get('level'),code:fd.get('code'),title:fd.get('title'),lecturer:fd.get('lecturer'),type:fd.get('type'),day:fd.get('day'),start:fd.get('start'),end:fd.get('end'),room:fd.get('room')};
    setTimetable(t=>[...t,item]); pushNotice(`New timetable published: ${item.code} · ${item.programme} ${item.level} Level · ${item.day} ${item.start}–${item.end}.`); setAdding(false);
  };

  const contextText = role==='Student'
    ? `${currentStudent.programme} · ${currentStudent.level} Level · ${currentStudent.session} · ${currentStudent.semester}`
    : role==='Lecturer' ? 'Dr. Ibrahim · all assigned teaching across programmes and levels · 2026/2027 First Semester'
    : canEdit ? `${filters.programme} · ${filters.level} Level · ${filters.session} · ${filters.semester}` : 'Computer Science · 300 Level · 2026/2027 First Semester';

  return <>
    <div className="page-heading"><div><span className="section-kicker">{canEdit?'ACADEMIC SCHEDULING':'LIVE ACADEMIC SCHEDULE'}</span><h1>{role==='Student'?'My timetable':role==='Lecturer'?'Teaching timetable':canEdit?'Timetable management':'University timetable'}</h1><p>{canEdit?'Manage the official timetable by session, semester, programme and level.':'Masta automatically shows the schedule that belongs to your academic or teaching profile.'}</p></div><div className="heading-actions"><div className="live-badge"><i></i> LIVE SYNC</div>{canEdit&&<button className="primary-btn" onClick={()=>setAdding(true)}>+ Add timetable entry</button>}</div></div>

    {canEdit&&<section className="schedule-filter panel"><div><span>Academic session</span><select value={filters.session} onChange={e=>setFilters(v=>({...v,session:e.target.value}))}><option>2026/2027</option></select></div><div><span>Semester</span><select value={filters.semester} onChange={e=>setFilters(v=>({...v,semester:e.target.value}))}><option>First Semester</option><option>Second Semester</option></select></div><div><span>Department</span><select value={filters.department} onChange={e=>setFilters(v=>({...v,department:e.target.value}))}><option>Computer Science</option><option>Software Engineering</option></select></div><div><span>Programme</span><select value={filters.programme} onChange={e=>setFilters(v=>({...v,programme:e.target.value}))}><option>B.Sc. Computer Science</option><option>B.Sc. Software Engineering</option></select></div><div><span>Level</span><select value={filters.level} onChange={e=>setFilters(v=>({...v,level:e.target.value}))}><option value="100">100 Level</option><option value="200">200 Level</option><option value="300">300 Level</option><option value="400">400 Level</option></select></div></section>}

    <div className="schedule-context"><span>{role==='Student'?'AUTO-ASSIGNED STUDENT VIEW':role==='Lecturer'?'LECTURER ALLOCATION':'CURRENT TIMETABLE VIEW'}</span><b>{contextText}</b>{role==='Student'&&<small>No level selector is shown to students. This timetable is generated from Amina's profile and registered courses.</small>}</div>
    <div className="notice-strip"><b>Real-time timetable</b><span>{canEdit?'Registry / Admin controls the official timetable. Switch between Computer Science 100, 200, 300 and 400 Level above; published changes sync to affected users.':role==='Lecturer'?'Your teaching timetable combines every course allocated to you, even across different departments and levels.':'Schedule changes are reflected immediately from the official academic timetable.'}</span></div>
    <div className="week-grid">{days.map(day=><section className="day-col" key={day}><div className="day-head"><b>{day}</b><span>{visibleTimetable.filter(x=>x.day===day).length} classes</span></div>{visibleTimetable.filter(x=>x.day===day).sort((a,b)=>a.start.localeCompare(b.start)).map(item=><div className={`class-card ${item.type==='Lab'?'lab':''}`} key={item.id}><div className="class-time">{item.start} — {item.end}</div><span>{item.code} · {item.type}</span><b>{item.title}</b><small>{item.programme} · {item.level} Level</small><small>{item.room}</small><small>{item.lecturer}</small>{canEdit&&<button onClick={()=>setEditing(item)}>Edit timetable</button>}</div>)}{!visibleTimetable.some(x=>x.day===day)&&<Empty title="No classes" text="Nothing scheduled"/>}</section>)}</div>

    {adding&&<Modal title="Add timetable entry" subtitle="Assign the class to the correct academic context before publishing." onClose={()=>setAdding(false)}><form className="form-grid" onSubmit={addClass}><label>Academic session<select name="session" defaultValue={filters.session}><option>2026/2027</option></select></label><label>Semester<select name="semester" defaultValue={filters.semester}><option>First Semester</option><option>Second Semester</option></select></label><label>Department<select name="department" defaultValue={filters.department}><option>Computer Science</option><option>Software Engineering</option></select></label><label>Programme<select name="programme" defaultValue={filters.programme}><option>B.Sc. Computer Science</option><option>B.Sc. Software Engineering</option></select></label><label>Level<select name="level" defaultValue={filters.level}><option value="100">100 Level</option><option value="200">200 Level</option><option value="300">300 Level</option><option value="400">400 Level</option></select></label><label>Course code<input name="code" required placeholder="e.g. CSC309"/></label><label className="span-2">Course title<input name="title" required/></label><label>Lecturer<input name="lecturer" required placeholder="e.g. Dr. Ibrahim"/></label><label>Class type<select name="type"><option>Lecture</option><option>Lab</option><option>Tutorial</option><option>Seminar</option></select></label><label>Day<select name="day">{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Room / venue<input name="room" required/></label><label>Start time<input name="start" type="time" required defaultValue="09:00"/></label><label>End time<input name="end" type="time" required defaultValue="11:00"/></label><div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary-btn">Publish timetable entry</button></div></form></Modal>}

    {editing&&<Modal title={`Edit ${editing.code}`} subtitle={`${editing.programme} · ${editing.level} Level`} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={saveEdit}><label>Academic session<select name="session" defaultValue={editing.session}><option>2026/2027</option></select></label><label>Semester<select name="semester" defaultValue={editing.semester}><option>First Semester</option><option>Second Semester</option></select></label><label>Department<select name="department" defaultValue={editing.department}><option>Computer Science</option><option>Software Engineering</option></select></label><label>Programme<select name="programme" defaultValue={editing.programme}><option>B.Sc. Computer Science</option><option>B.Sc. Software Engineering</option></select></label><label>Level<select name="level" defaultValue={editing.level}><option value="100">100 Level</option><option value="200">200 Level</option><option value="300">300 Level</option><option value="400">400 Level</option></select></label><label>Course code<input name="code" required defaultValue={editing.code}/></label><label className="span-2">Course title<input name="title" required defaultValue={editing.title}/></label><label>Lecturer<input name="lecturer" required defaultValue={editing.lecturer}/></label><label>Class type<select name="type" defaultValue={editing.type}><option>Lecture</option><option>Lab</option><option>Tutorial</option><option>Seminar</option></select></label><label>Day<select name="day" defaultValue={editing.day}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Room / venue<input name="room" required defaultValue={editing.room}/></label><label>Start time<input name="start" type="time" required defaultValue={editing.start}/></label><label>End time<input name="end" type="time" required defaultValue={editing.end}/></label><div className="form-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-btn">Publish changes</button></div></form></Modal>}
  </>;
}

function Registration(){return <><div className="page-heading"><div><span className="section-kicker">COURSE REGISTRATION</span><h1>Registration control</h1><p>Monitor registration completion, exceptions and adviser approvals.</p></div><button className="soft-btn">Registration closes · 10 Sep</button></div><div className="kpi-grid"><Kpi label="Eligible students" value="14,210" meta="This semester"/><Kpi label="Completed" value="12,936" meta="91.0% of eligible students" tone="green"/><Kpi label="Awaiting adviser" value="486" meta="Across 22 departments"/><Kpi label="Not started" value="788" meta="Follow-up recommended" tone="amber"/></div><section className="panel"><div className="panel-head"><div><h3>Registration exceptions</h3><p>Students who require an intervention before registration can complete.</p></div><button>Send reminders</button></div>{[['Aisha Nwosu','Prerequisite exception','CSC405 · Machine Learning','Adviser review'],['Ibrahim Sani','Credit overload','26 credits selected','HOD approval'],['Emeka Obi','Finance hold','₦120,000 outstanding','Bursary'],['Maryam Lawal','Timetable conflict','ECO311 / STA305','Department']].map(x=><div className="workflow-row" key={x[0]}><div className="avatar">{initials(x[0])}</div><div><b>{x[0]}</b><small>{x[2]}</small></div><span>{x[1]}</span><em>{x[3]}</em><button>Review →</button></div>)}</section></>}

function TranscriptModal({ onClose }) {
  const credits=gradeRows.reduce((a,r)=>a+r[2],0), points=gradeRows.reduce((a,r)=>a+r[5],0), cgpa=(points/credits).toFixed(2);
  const print=()=>window.print();
  return <Modal title="Official Academic Transcript" subtitle="Masta Demo University · Student Copy" onClose={onClose} wide><div id="transcript" className="transcript"><div className="transcript-brand"><div className="brand-mark small">M</div><div><h2>MASTA DEMO UNIVERSITY</h2><p>Office of the Registrar · Academic Transcript</p></div></div><div className="transcript-meta"><div><span>Student</span><b>Amina Bello</b></div><div><span>Matriculation No.</span><b>MST/23/0412</b></div><div><span>Programme</span><b>B.Sc. Computer Science</b></div><div><span>Current CGPA</span><b>{cgpa}</b></div></div><table><thead><tr><th>Course</th><th>Title</th><th>Credits</th><th>Grade</th><th>Points</th></tr></thead><tbody>{gradeRows.map((r,i)=><tr key={i}><td>{r[0]}</td><td>{['Data Structures','Computer Architecture','Object-Oriented Programming','Discrete Mathematics','Communication Skills','Web Technologies','Computer Networks','Systems Analysis','Linear Algebra','Leadership Studies'][i]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{r[5]}</td></tr>)}</tbody></table><div className="transcript-summary"><span>Total credits: <b>{credits}</b></span><span>Total quality points: <b>{points}</b></span><span>CGPA: <b>{cgpa}</b></span></div><div className="verification-note">Digitally generated by Masta UniversityOS · Verification ID: MDU-TR-260904-0412</div></div><div className="modal-actions"><button onClick={onClose}>Close</button><button className="primary-btn" onClick={print}>Print / Save PDF</button></div></Modal>;
}

function Results({ role }) {
  const [transcript,setTranscript]=useState(false);
  if(role==='Student') return <><div className="page-heading"><div><span className="section-kicker">ACADEMIC RECORD</span><h1>Results & transcript</h1><p>Review your results, GPA progression and generate your academic transcript.</p></div><button className="primary-btn" onClick={()=>setTranscript(true)}>Generate transcript</button></div><div className="kpi-grid"><Kpi label="Current CGPA" value="4.21" meta="+0.12 from previous session" tone="green"/><Kpi label="Credits earned" value="94" meta="120 required for graduation"/><Kpi label="Courses passed" value="31" meta="2 currently in progress"/><Kpi label="Academic standing" value="Good" meta="No academic restrictions" tone="green"/></div><section className="panel table-panel"><div className="panel-head table-head"><div><h3>Academic history</h3><p>Completed courses and grades.</p></div><button>2025/26 · Second Semester⌄</button></div><table><thead><tr><th>Course</th><th>Title</th><th>Credits</th><th>Grade</th><th>Quality points</th></tr></thead><tbody>{gradeRows.slice(0,5).map((r,i)=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{['Data Structures','Computer Architecture','Object-Oriented Programming','Discrete Mathematics','Communication Skills'][i]}</td><td>{r[2]}</td><td><span className="grade">{r[3]}</span></td><td>{r[5]}</td></tr>)}</tbody></table></section>{transcript&&<TranscriptModal onClose={()=>setTranscript(false)}/>}</>;
  return <><div className="page-heading"><div><span className="section-kicker">RESULTS & APPROVALS</span><h1>Academic results</h1><p>Controlled grade submission, review, approval and publication.</p></div><button className="primary-btn">Open grade window</button></div><div className="approval-flow">{[['1','Lecturer submission','126 batches'],['2','Department review','38 batches'],['3','Faculty verification','18 batches'],['4','Publication','9 approved']].map((x,i)=><React.Fragment key={x[0]}><div className={i<2?'active':''}><i>{x[0]}</i><b>{x[1]}</b><span>{x[2]}</span></div>{i<3&&<strong>→</strong>}</React.Fragment>)}</div><section className="panel"><div className="panel-head"><div><h3>Pending grade batches</h3><p>Most recent submissions requiring action.</p></div><button>View all</button></div>{[['CSC301','Algorithms','Dr. Musa Ibrahim','86','Department review'],['ECO305','Econometrics I','Dr. K. Adebayo','74','Faculty verification'],['LAW411','Company Law','Dr. N. Bello','63','Department review']].map(x=><div className="result-row" key={x[0]}><code>{x[0]}</code><div><b>{x[1]}</b><small>{x[2]}</small></div><span>{x[3]} students</span><em>{x[4]}</em><button>Review</button></div>)}</section></>;
}

function Finance({ role }) { const student=role==='Student'; return <><div className="page-heading"><div><span className="section-kicker">{student?'MY FINANCES':'STUDENT FINANCE'}</span><h1>{student?'Fees & payments':'Finance'}</h1><p>{student?'Track charges, payments, balances and receipts.':'Monitor institutional fee collection and student accounts.'}</p></div><button className="primary-btn">{student?'Make payment':'Create fee item'}</button></div><div className="kpi-grid"><Kpi label={student?'Total billed':'Expected fees'} value={student?'₦725,000':'₦8.7bn'} meta="2026/27 session"/><Kpi label={student?'Paid':'Collected'} value={student?'₦650,000':'₦7.2bn'} meta={student?'89.7% paid':'82.8% collection'} tone="green"/><Kpi label="Outstanding" value={student?'₦75,000':'₦1.5bn'} meta="Payment follow-up" tone="amber"/><Kpi label={student?'Next due':'Payment completion'} value={student?'30 Sep':'11,904'} meta={student?'Final instalment':'students fully paid'}/></div><section className="panel"><div className="panel-head"><div><h3>{student?'Account statement':'Collection by fee category'}</h3><p>2026/27 academic session.</p></div><button>{student?'Download statement':'Export report'}</button></div>{student?[['Tuition','₦650,000','Paid'],['ICT Levy','₦35,000','Paid'],['Library & Student Services','₦40,000','₦75,000 balance']].map(x=><div className="finance-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><em>{x[2]}</em></div>):[['Tuition','₦6.34bn','86%'],['Accommodation','₦420m','79%'],['ICT levy','₦231m','91%'],['Other student services','₦209m','72%']].map(x=><div className="progress-row" key={x[0]}><span>{x[0]}</span><div className="bar"><i style={{width:x[2]}}></i></div><b>{x[1]}</b></div>)}</section></> }

function Registry(){return <><div className="page-heading"><div><span className="section-kicker">REGISTRY OPERATIONS</span><h1>Registry</h1><p>Manage authoritative student status changes and official requests.</p></div><button className="primary-btn">+ New registry action</button></div><div className="kpi-grid"><Kpi label="Open requests" value="126" meta="Across all workflow types"/><Kpi label="Programme changes" value="34" meta="21 awaiting department action"/><Kpi label="Graduation reviews" value="612" meta="Final-year students"/><Kpi label="Clearance complete" value="81%" meta="For graduating cohort" tone="green"/></div><section className="panel"><div className="panel-head"><div><h3>Recent requests</h3><p>Status-changing requests requiring registry action.</p></div><button>View queue</button></div>{[['Zainab Ibrahim','Graduation eligibility review','Faculty verified','High'],['Chika Nwankwo','Programme transfer','HOD approved','Normal'],['Suleiman Garba','Deferment request','Documents verified','Normal'],['Grace Peter','Name correction','Identity check','Normal']].map(x=><div className="registry-row" key={x[0]}><div className="avatar">{initials(x[0])}</div><div><b>{x[0]}</b><small>{x[1]}</small></div><span>{x[2]}</span><em>{x[3]}</em><button>Open →</button></div>)}</section></>}

function Advising(){return <><div className="page-heading"><div><span className="section-kicker">ACADEMIC ADVISING</span><h1>Student success</h1><p>Surface risk early and help advisers intervene with context.</p></div><button className="soft-btn">My advisees · 42⌄</button></div><div className="kpi-grid"><Kpi label="My advisees" value="42" meta="Computer Science"/><Kpi label="Good standing" value="34" meta="81% of advisees" tone="green"/><Kpi label="Needs attention" value="6" meta="Academic or registration risk" tone="amber"/><Kpi label="High risk" value="2" meta="Intervention recommended" tone="amber"/></div><section className="panel"><div className="panel-head"><div><h3>Students requiring attention</h3><p>Prioritised using academic and administrative signals.</p></div><button>Risk methodology</button></div>{[['Mohammed Umar','1.72','Low CGPA · 3 failed courses','High'],['David James','3.12','Registration incomplete','Medium'],['Hadiza Ali','2.04','Attendance below 70%','Medium']].map(x=><div className="risk-row" key={x[0]}><div className="avatar">{initials(x[0])}</div><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>CGPA {x[1]}</strong><span className={`risk ${x[3].toLowerCase()}`}>{x[3]} risk</span><button>Review</button></div>)}</section></>}

function Resources({ role, materials, setMaterials, pushNotice }) {
  const [open,setOpen]=useState(null); const [upload,setUpload]=useState(false); const lecturer=role==='Lecturer';
  const addMaterial=(e)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const m={id:Date.now(),code:fd.get('code'),title:fd.get('title'),kind:fd.get('kind'),size:'1.2 MB',date:'04 Sep 2026',lecturer:'Dr. Musa Ibrahim'}; setMaterials(v=>[m,...v]); pushNotice(`New learning material published for ${m.code}: ${m.title}`); setUpload(false);};
  return <><div className="page-heading"><div><span className="section-kicker">DIGITAL RESOURCE CENTRE</span><h1>{lecturer?'Course materials':'Documents & learning materials'}</h1><p>{lecturer?'Publish and manage resources for your students.':'Access official student documents and the latest lesson materials from your courses.'}</p></div>{lecturer&&<button className="primary-btn" onClick={()=>setUpload(true)}>+ Upload material</button>}</div>
    {!lecturer&&<><h3 className="subsection-title">My documents</h3><div className="resource-grid docs">{documentsSeed.map(d=><article className="resource-card" key={d.id}><div className="file-icon">PDF</div><span>{d.category}</span><h3>{d.title}</h3><p>Issued {d.date}</p><div><button onClick={()=>setOpen(d)}>Open</button><button>Download</button></div></article>)}</div></>}
    <div className="subsection-row"><h3 className="subsection-title">{lecturer?'Published materials':'Lesson materials'}</h3><button>All courses⌄</button></div><div className="resource-list">{materials.map(m=><div className="material-row" key={m.id}><div className="file-icon soft">{m.kind.includes('slide')?'PPT':'DOC'}</div><div><span className="course-chip">{m.code}</span><b>{m.title}</b><small>{m.kind} · {m.size} · {m.lecturer}</small></div><em>{m.date}</em><button onClick={()=>setOpen(m)}>Open</button><button>↓</button></div>)}</div>
    {open&&<Modal title={open.title} subtitle={open.code?`${open.code} · ${open.kind}`:`${open.category} document`} onClose={()=>setOpen(null)} wide><div className="doc-preview"><div className="doc-sheet"><div className="brand-mark small">M</div><span>MASTA DEMO UNIVERSITY</span><h2>{open.title}</h2><p>This is a demonstration preview of the selected {open.kind||open.category} file. In the production Masta UniversityOS, authorised files will be securely stored, versioned and delivered from institutional object storage.</p><div className="preview-lines"><i></i><i></i><i></i><i></i><i></i></div></div></div><div className="modal-actions"><button onClick={()=>setOpen(null)}>Close</button><button className="primary-btn">Download file</button></div></Modal>}
    {upload&&<Modal title="Publish lesson material" subtitle="Students enrolled in the selected course will see it immediately." onClose={()=>setUpload(false)}><form className="form-grid" onSubmit={addMaterial}><label>Course<select name="code">{courses.slice(0,4).map(c=><option key={c.code}>{c.code}</option>)}</select></label><label>Material type<select name="kind"><option>Lecture slides</option><option>Lecture notes</option><option>Reading</option><option>Worksheet</option></select></label><label className="span-2">Title<input name="title" required placeholder="e.g. Week 2 — Divide and Conquer"/></label><label className="span-2">File<div className="fake-upload">＋ Choose file <small>PDF, PPTX, DOCX · demo only</small></div></label><div className="form-actions"><button type="button" onClick={()=>setUpload(false)}>Cancel</button><button className="primary-btn">Publish material</button></div></form></Modal>}
  </>;
}

function Attendance({ role, attendanceRecords, setAttendanceRecords, pushNotice }) {
  const [course,setCourse]=useState('CSC301'); const [roster,setRoster]=useState(attendanceStudentsSeed); const [saved,setSaved]=useState(false);
  const lecturer=role==='Lecturer';
  const toggle=id=>setRoster(r=>r.map(s=>s.id===id?{...s,present:!s.present}:s));
  const save=()=>{ const record={id:Date.now(),code:course,date:'04 Sep 2026',time:'09:00',present:roster.filter(s=>s.present).length,total:roster.length}; setAttendanceRecords(v=>[record,...v]); setSaved(true); pushNotice(`Attendance recorded for ${course}: ${record.present}/${record.total} students present.`); setTimeout(()=>setSaved(false),2200); };
  if(!lecturer) return <><div className="page-heading"><div><span className="section-kicker">ATTENDANCE RECORD</span><h1>My attendance</h1><p>Track your course attendance and eligibility status.</p></div></div><div className="kpi-grid"><Kpi label="Overall attendance" value="92%" meta="Above required threshold" tone="green"/><Kpi label="Classes attended" value="46" meta="Out of 50 sessions"/><Kpi label="Missed classes" value="4" meta="Across 3 courses"/><Kpi label="Minimum required" value="75%" meta="University policy"/></div><section className="panel"><div className="panel-head"><div><h3>Attendance by course</h3><p>Current semester.</p></div></div>{courses.slice(0,5).map((c,i)=><div className="attendance-course" key={c.code}><div><span className="course-chip">{c.code}</span><b>{c.title}</b></div><div className="bar"><i style={{width:`${[96,90,88,94,91][i]}%`}}></i></div><strong>{[96,90,88,94,91][i]}%</strong><span className="status">Eligible</span></div>)}</section></>;
  return <><div className="page-heading"><div><span className="section-kicker">LECTURER ATTENDANCE</span><h1>Take attendance</h1><p>Record class attendance and maintain a permanent session history.</p></div><button className="soft-btn">04 Sep 2026 · 09:00</button></div><div className="attendance-toolbar"><label>Course<select value={course} onChange={e=>setCourse(e.target.value)}>{courses.slice(0,4).map(c=><option key={c.code}>{c.code} · {c.title}</option>)}</select></label><div><span>Present</span><b>{roster.filter(s=>s.present).length}/{roster.length}</b></div><button onClick={()=>setRoster(r=>r.map(s=>({...s,present:true})))}>Mark all present</button><button className="primary-btn" onClick={save}>{saved?'✓ Attendance saved':'Save attendance'}</button></div><section className="panel attendance-panel"><div className="panel-head"><div><h3>Class roster</h3><p>Tap a student's status to mark present or absent.</p></div><span className="metric-chip">{Math.round(roster.filter(s=>s.present).length/roster.length*100)}% present</span></div>{roster.map((s,i)=><div className="roster-row" key={s.id}><span>{String(i+1).padStart(2,'0')}</span><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><small>{s.id}</small></div><button className={`attendance-toggle ${s.present?'present':'absent'}`} onClick={()=>toggle(s.id)}>{s.present?'✓ Present':'× Absent'}</button></div>)}</section><section className="panel history-panel"><div className="panel-head"><div><h3>Attendance history</h3><p>Saved sessions for your courses.</p></div></div>{attendanceRecords.map(r=><div className="history-row" key={r.id}><span className="course-chip">{r.code}</span><b>{r.date}</b><span>{r.time}</span><span>{r.present}/{r.total} present</span><strong>{Math.round(r.present/r.total*100)}%</strong></div>)}</section></>;
}

function Assignments({ role, assignments, setAssignments, pushNotice }) {
  const lecturer=role==='Lecturer'; const [create,setCreate]=useState(false); const [selected,setSelected]=useState(null); const [submitted,setSubmitted]=useStoredState('masta-demo-submitted',[]);
  const add=(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const a={id:Date.now(),code:fd.get('code'),title:fd.get('title'),due:fd.get('due'),points:Number(fd.get('points')),status:'Open',instructions:fd.get('instructions'),submissions:0};setAssignments(v=>[a,...v]);pushNotice(`New assignment published: ${a.code} — ${a.title}, due ${fmtDate(a.due)}.`);setCreate(false);};
  const submit=id=>{setSubmitted(v=>[...new Set([...v,id])]);pushNotice('Assignment submitted successfully. Your lecturer can now view the submission.');setSelected(null);};
  return <><div className="page-heading"><div><span className="section-kicker">COURSEWORK</span><h1>{lecturer?'Assignments':'My assignments'}</h1><p>{lecturer?'Create coursework, track submissions and manage deadlines.':'View coursework, instructions, deadlines and submission status.'}</p></div>{lecturer&&<button className="primary-btn" onClick={()=>setCreate(true)}>+ Create assignment</button>}</div><div className="assignment-grid">{assignments.map(a=><article className="assignment-card" key={a.id}><div className="assignment-top"><span className="course-chip">{a.code}</span><span className={`status ${new Date(a.due)<new Date()?'warn':''}`}>{submitted.includes(a.id)?'Submitted':a.status}</span></div><h3>{a.title}</h3><p>{a.instructions}</p><div className="assignment-meta"><span><small>Due</small><b>{fmtDate(a.due)}</b></span><span><small>Points</small><b>{a.points}</b></span><span><small>{lecturer?'Submissions':'Status'}</small><b>{lecturer?`${a.submissions}/${courses.find(c=>c.code===a.code)?.students||86}`:(submitted.includes(a.id)?'Received':'Not submitted')}</b></span></div><button onClick={()=>setSelected(a)}>{lecturer?'View submissions →':submitted.includes(a.id)?'View submission':'Open assignment →'}</button></article>)}</div>
    {selected&&!lecturer&&<Modal title={selected.title} subtitle={`${selected.code} · Due ${fmtDate(selected.due)}`} onClose={()=>setSelected(null)}><div className="assignment-detail"><span>INSTRUCTIONS</span><p>{selected.instructions}</p><div className="fake-upload">＋ Attach submission <small>PDF, DOCX, ZIP · demo only</small></div></div><div className="modal-actions"><button onClick={()=>setSelected(null)}>Close</button>{!submitted.includes(selected.id)&&<button className="primary-btn" onClick={()=>submit(selected.id)}>Submit assignment</button>}</div></Modal>}
    {selected&&lecturer&&<Modal title={`${selected.code} submissions`} subtitle={selected.title} onClose={()=>setSelected(null)}><div className="submission-list">{attendanceStudentsSeed.slice(0,5).map((s,i)=><div key={s.id}><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><small>{i<3?'Submitted 03 Sep · 18:2'+i:'Not submitted'}</small></div><span className={`status ${i>=3?'pending':''}`}>{i<3?'Received':'Pending'}</span><button>{i<3?'Review':'—'}</button></div>)}</div></Modal>}
    {create&&<Modal title="Create assignment" subtitle="It will be visible to enrolled students immediately." onClose={()=>setCreate(false)}><form className="form-grid" onSubmit={add}><label>Course<select name="code">{courses.slice(0,4).map(c=><option key={c.code}>{c.code}</option>)}</select></label><label>Points<input name="points" type="number" defaultValue="20" min="1"/></label><label className="span-2">Assignment title<input name="title" required/></label><label>Due date<input name="due" type="date" defaultValue="2026-09-15" required/></label><label>Status<select><option>Open</option></select></label><label className="span-2">Instructions<textarea name="instructions" rows="4" required></textarea></label><div className="form-actions"><button type="button" onClick={()=>setCreate(false)}>Cancel</button><button className="primary-btn">Publish assignment</button></div></form></Modal>}
  </>;
}

function Analytics(){return <><div className="page-heading"><div><span className="section-kicker">MASTA INTELLIGENCE</span><h1>Institutional intelligence</h1><p>Turn operational university data into timely decisions.</p></div><button className="soft-btn">Last refreshed · 2 min ago</button></div><div className="insight-hero"><div><span>MASTA INSIGHT</span><h2>38 students show a high probability of academic disengagement.</h2><p>The strongest combined signals are declining attendance, multiple failed prerequisites and incomplete registration. 24 students have not yet received a recorded adviser intervention.</p></div><button>Review cohort →</button></div><div className="dashboard-grid three"><section className="panel insight-card"><span>RETENTION</span><b>94.2%</b><p>Current year retention rate</p><small>↑ 1.8 pts YoY</small></section><section className="panel insight-card"><span>GRADUATION READINESS</span><b>83%</b><p>Final-year cohort currently eligible</p><small>612 under review</small></section><section className="panel insight-card"><span>REGISTRATION</span><b>91.4%</b><p>Registration completion</p><small>6 days to deadline</small></section></div><section className="panel"><div className="panel-head"><div><h3>Institutional signals</h3><p>Patterns Masta is surfacing from across university operations.</p></div><button>Explore analytics</button></div>{[['01','CSC205 has a 31% failure rate, 2.1× the faculty average','Academic'],['02','Fee completion is 14% lower among new postgraduate students','Finance'],['03','Tuesday 8am classes show the highest absence rate','Attendance']].map(x=><div className="signal-row" key={x[0]}><i>{x[0]}</i><span>{x[1]}</span><b>{x[2]}</b></div>)}</section></>}

export default function Dashboard({ onLogout }) {
  const [active,setActive]=useState('Overview'); const [role,setRole]=useStoredState('masta-demo-role','University Management'); const [sidebar,setSidebar]=useState(false);
  const [timetable,setTimetable]=useStoredState('masta-demo-timetable-v04',timetableSeed); const [materials,setMaterials]=useStoredState('masta-demo-materials',materialsSeed); const [assignments,setAssignments]=useStoredState('masta-demo-assignments',assignmentsSeed); const [attendanceRecords,setAttendanceRecords]=useStoredState('masta-demo-attendance',[{id:1,code:'CSC301',date:'01 Sep 2026',time:'09:00',present:78,total:86},{id:2,code:'CSC303',date:'31 Aug 2026',time:'13:00',present:76,total:84}]);
  const [notifications,setNotifications]=useStoredState('masta-demo-notices',[{id:1,text:'Welcome to the Masta UniversityOS demonstration.',time:'Today'}]); const [showNotices,setShowNotices]=useState(false);
  const pushNotice=(text)=>setNotifications(n=>[{id:Date.now(),text,time:'Just now'},...n].slice(0,20));
  const changeRole=(r)=>{setRole(r);setActive('Overview');};
  const roleNav = role==='Lecturer' ? ['Overview','Timetable','Resources','Attendance','Assignments','Results','Students'] : role==='Student' ? ['Overview','Timetable','Registration','Results','Finance','Resources','Attendance','Assignments'] : role==='Finance' ? ['Overview','Students','Finance','Analytics'] : role==='Academic Adviser' ? ['Overview','Students','Timetable','Registration','Results','Advising','Analytics'] : coreNav;

  const render=()=>{
    if(active==='Overview') return role==='Student'?<StudentHome setActive={setActive} timetable={timetable} assignments={assignments}/>:<Overview setActive={setActive}/>;
    if(active==='Students') return <Students/>;
    if(active==='Academics') return <Academics/>;
    if(active==='Timetable') return <Timetable role={role} timetable={timetable} setTimetable={setTimetable} pushNotice={pushNotice}/>;
    if(active==='Registration') return <Registration/>;
    if(active==='Results') return <Results role={role}/>;
    if(active==='Finance') return <Finance role={role}/>;
    if(active==='Registry') return <Registry/>;
    if(active==='Advising') return <Advising/>;
    if(active==='Resources') return <Resources role={role} materials={materials} setMaterials={setMaterials} pushNotice={pushNotice}/>;
    if(active==='Attendance') return <Attendance role={role} attendanceRecords={attendanceRecords} setAttendanceRecords={setAttendanceRecords} pushNotice={pushNotice}/>;
    if(active==='Assignments') return <Assignments role={role} assignments={assignments} setAssignments={setAssignments} pushNotice={pushNotice}/>;
    return <Analytics/>;
  };

  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?'open':''}`}><div className="sidebar-brand"><span className="brand-mark">M</span><div><strong>Masta</strong><small>UniversityOS</small></div></div><div className="university-card"><span>MDU</span><div><b>Masta Demo University</b><small>Client demonstration</small></div></div><nav>{roleNav.map(n=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);setSidebar(false)}}><Icon name={n}/><span>{n}</span>{n==='Assignments'&&role==='Student'&&<em>{assignments.filter(a=>a.status==='Open').length}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="prototype-note"><span>DEMO ENVIRONMENT</span><p>Mock institutional data. No production records.</p></div><button className="logout" onClick={onLogout}>↗ <span>Sign out</span></button></div></aside>
    <main className="main-area"><header className="topbar"><button className="menu-btn" onClick={()=>setSidebar(v=>!v)}>☰</button><div className="breadcrumb"><span>Masta UniversityOS</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><div className="role-switch"><span>VIEWING AS</span><select value={role} onChange={e=>changeRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></div><div className="notice-wrap"><button className="icon-btn bell" onClick={()=>setShowNotices(v=>!v)}>♢<i>{notifications.length}</i></button>{showNotices&&<div className="notification-pop"><div><b>Notifications</b><button onClick={()=>setNotifications([])}>Clear</button></div>{notifications.length?notifications.slice(0,6).map(n=><article key={n.id}><i></i><p>{n.text}<small>{n.time}</small></p></article>):<Empty title="All caught up" text="No new notifications"/>}</div>}</div><div className="profile"><span>PA</span><div><b>{role==='Student'?'Amina Bello':role==='Lecturer'?'Dr. Ibrahim':'Prof. Adeyemi'}</b><small>{role}</small></div></div></div></header><div className="content">{render()}</div><footer className="demo-footer"><span>Masta UniversityOS</span><span>The digital operating and intelligence layer for modern universities.</span><span>Prototype · v0.4</span></footer></main>
  </div>;
}
